# Generated by Django 2.0.2 on 2018-03-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpisokMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sushiname', models.CharField(max_length=200)),
                ('resept', models.TextField(help_text='SushiResept', max_length=1000)),
                ('sushiprice', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">SushiPrice number</a>', max_length=13, verbose_name='SushiPrice')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=100)),
                ('sponsor_kala', models.CharField(max_length=100)),
                ('zakaz_product', models.DateField(blank=True, null=True)),
                ('printitya_zakaz', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['sponsor_kala', 'sponsor_name'],
            },
        ),
        migrations.CreateModel(
            name='Sushitype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dobavite type sushi (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='spisokmenu',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Sponsor'),
        ),
        migrations.AddField(
            model_name='spisokmenu',
            name='sushitype',
            field=models.ManyToManyField(help_text='Sushitype', to='catalog.Sushitype'),
        ),
    ]
